version: '3.4'

services:
  hybookify.api:
    image: ${DOCKER_REGISTRY-}hybookifyapi
    container_name: hyBookify.Api
    build:
      context: .
      dockerfile: hyBookify.Api/Dockerfile
    depends_on:
      - hybookify-db

  hybookify-db:
    image: postgres:16-alpine
    container_name: hyBookify.Db
    environment:
      - POSTGRES_DB=hybookify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432