version: '3.4'

services:
  hybookify.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
    ports:
      - 5002:5000
      - 5001:5001
    volumes:
      - ${APPDATA:-~}/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA:-~}/.aspnet/https:/root/.aspnet/https:ro